package model.enums;

public enum TeamName {
    Russia,
    Brazil,
    Iran,
    Japan,
    Mexico,
    Belgium,
    South_Korea,
    Saudi_Arabia,
    Germany,
    England,
    Spain,
    Nigeria,
    Costa_Rica,
    Poland,
    Egypt,
    Iceland,
    Serbia,
    Portugal,
    France,
    Uruguay,
    Argentina,
    Colombia,
    Panama,
    Senegal,
    Morocco,
    Tunisia,
    Switzerland,
    Croatia,
    Sweden,
    Denmark,
    Australia,
    Peru,
    A1,A2,B1,B2,C1,C2,D1,D2,E1,E2,F1,F2,G1,G2,H1,H2,
    W49,W50,W51,W52,W53,W54,W55,W56,W57,W58,W59,W60,W61,W62,L61,L62
}
